version: "2.3"

services:

  dds_router:
    build: .
    environment:
      - DS_HOSTNAME=my-discovery-server-hostname
    volumes:
      - ./router-config.yaml:/config.yaml
    command: bash -c "/wait_ds.sh && ddsrouter -c /config.yaml -r 10"