version: v2.0

allowlist:
  
  - name: "*"

participants:
  
  - name: LocalParticipant
    kind: local
    domain: 0

  - name: ServerWAN
    kind: local-discovery-server
    discovery-server-guid:
      id: 0
      ros-discovery-server: true
    listening-addresses:
      - domain: localhost
        port: 11811
